plugins: ['@typescript-eslint']
extends:
  [
    'eslint:recommended',
    'plugin:@typescript-eslint/recommended',
    'plugin:import/recommended',
    'prettier',
  ]
parser: '@typescript-eslint/parser'
parserOptions:
  project: ['tsconfig.json']
root: true
settings:
  import/resolver:
    - typescript
rules:
  '@typescript-eslint/ban-ts-comment': warn
  '@typescript-eslint/explicit-function-return-type': off
  '@typescript-eslint/no-var-requires': warn
  '@typescript-eslint/return-await': off
  '@typescript-eslint/no-this-alias': warn
  import/order:
    - warn
    - newlines-between: always
  import/newline-after-import: warn
  no-case-declarations: warn
  no-console: warn
  no-empty:
    - error
    - allowEmptyCatch: true
  no-useless-constructor: warn
